import type { CategoryKey } from "@/lib/categories";

export type PhotoStatus = "processing" | "ready";

export interface Photo {
  id: string;
  drive_file_id: string | null;
  drive_name: string | null;
  object_key: string | null;
  storage_backend: string | null;
  display_name: string | null;
  thumbnail_path: string | null;
  tags: string[] | null;
  description: string | null;
  category: CategoryKey | null;
  current_folder_id: string | null;
  moved_at: string | null;
  perceptual_hash: string | null;
  duplicate_group_id: string | null;
  status: PhotoStatus;
  picked: boolean;
  picked_at: string | null;
  posted: boolean | null;
  created_at: string;
  // Whether the AI is allowed to overlay text on this photo (good exposure,
  // clear subject, simple enough background). User toggles per-photo on the board.
  text_safe: boolean;
}

// A saved graphic generated by the in-app design tool.
export interface Graphic {
  id: string;
  design_spec: Record<string, unknown>;
  png_path: string | null;
  size: "feed" | "story";
  status: string;
  created_at: string;
}
